export const PUT_USER = "AUTH/PUT-USER";
export const PUT_AUTH_ERROR = "AUTH/PUT-ERROR";
export const CLEAR_AUTH_ERROR = "AUTH/CLEAR-ERROR";
export const LOG_USER = "AUTH/USER-LOGIN";
export const LOG_USER_CRED = "AUTH/USER-LOGIN-WITH-CRED";
export const LOGOUT_USER = "AUTH/USER-LOGOUT";
export const ALLOW_ACCESS = "AUTH/USER-ACCESS-ALLOWED";
export const RESTRICT_ACCESS = "AUTH/USER-ACCESS-RESTRICTED";

export const UPLOAD_FILE = "FILES/UPLOAD-FILE";
export const NEW_FILES = "FILES/NEW-FILES";
export const DELETE_FILE = "FILES/DELETE-FILE";
export const FETCH_FILES = "FILES/FETCH-ALL-FILES";
export const PUT_FILES = "FILES/PUT-FILES";
export const CLEAR_FILES = "FILES/CLEAR-ALL-FILES";
export const UPDATE_SPACE_USAGE = "FILES/UPDATE-SPACE-USAGE";
export const CLEAR_SPACE_USAGE = "FILES/CLEAR-SPACE-USAGE";
export const SET_SPACE_USAGE = "FILES/SET-SPACE-USAGE";
export const SET_UPL_MESSAGE = "FILES/SET-UPLOAD-MESSAGE";

export const PUT_FILENAME_FOR_DETAILS = "DETAILS/PUT-FILENAME";
export const CLEAR_FILENAME_FOR_DETAILS = "DETAILS/CLEAR-FILENAME";
export const FILE_WAS_DELETED = "DETAILS/DELETE-FILE-ACTION";


export const PUT_NUMERIC_COLUMNS = "CSV-TABLE/PUT-NUM-COLUMNS";
export const PUT_ALL_COLUMNS = "CSV-TABLE/PUT-ALL-COLUMNS";

export const SHOW_PAGE_LOADER = "PAGE-LOADER/SHOW-LOADER";
export const HIDE_PAGE_LOADER = "PAGE-LOADER/HIDE-LOADER";
