export const PUT_USER = "AUTH/PUT-USER";
export const PUT_AUTH_ERROR = "AUTH/PUT-ERROR";
export const CLEAR_AUTH_ERROR = "AUTH/CLEAR-ERROR";
export const LOG_USER = "AUTH/USER-LOGIN";
export const LOG_USER_CRED = "AUTH/USER-LOGIN-WITH-CRED";
export const LOGOUT_USER = "AUTH/USER-LOGOUT";
export const ALLOW_ACCESS = "AUTH/USER-ACCESS-ALLOWED";
export const RESTRICT_ACCESS = "AUTH/USER-ACCESS-RESTRICTED";

export const UPLOAD_FILE = "FILES/UPLOAD-FILE";
export const NEW_FILES = "FILES/NEW-FILES";
export const DELETE_FILE = "FILES/DELETE-FILE";
export const FETCH_FILES = "FILES/FETCH-ALL-FILES";
export const PUT_FILES = "FILES/PUT-FILES";
export const CLEAR_FILES = "FILES/CLEAR-ALL-FILES";
export const UPDATE_SPACE_USAGE = "FILES/UPDATE-SPACE-USAGE";
export const CLEAR_SPACE_USAGE = "FILES/CLEAR-SPACE-USAGE";
export const SET_SPACE_USAGE = "FILES/SET-SPACE-USAGE";
export const SET_UPL_MESSAGE = "FILES/SET-UPLOAD-MESSAGE";

export const PUT_FILENAME_FOR_DETAILS = "DETAILS/PUT-FILENAME";
export const CLEAR_FILENAME_FOR_DETAILS = "DETAILS/CLEAR-FILENAME";

export const PUT_CSV_TABLE = "CSV-TABLE/PUT-TABLE";
export const PUT_NUMERIC_COLUMNS = "CSV-TABLE/PUT-NUM-COLUMNS";
export const CLEAR_CSV_TABLE = "CSV-TABLE/CLEAR-TABLE";
export const HIDE_CSV_TABLE = "CSV-TABLE/HIDE-TABLE";
export const SHOW_CSV_TABLE = "CSV-TABLE/SHOW-TABLE";

export const SHOW_PAGE_LOADER = "PAGE-LOADER/SHOW-LOADER";
export const HIDE_PAGE_LOADER = "PAGE-LOADER/HIDE-LOADER";


export const CLEAR_GRAPH = "GRAPH/CLEAR-GRAPH";
export const FETCH_HISTOGRAMM = "GRAPH/FETCH-HISTOGRAMM";
export const CLEAR_HISTOGRAMM = "GRAPH/CLEAR-HISTOGRAMM";
export const PUT_HISTOGRAMM = "GRAPH/PUT-HISTOGRAMM";
export const FETCH_SCATTER = "GRAPH/FETCH-SCATTER";
export const CLEAR_SCATTER = "GRAPH/CLEAR-SCATTER";
export const PUT_SCATTER = "GRAPH/PUT-SCATTER";